cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.jdk"
sudo: false
env:
  global:
  - TARGET=install
  - JDKW=https://raw.githubusercontent.com/vjkoskela/jdk-wrapper/master/jdk-wrapper.sh
install: true
before_script:
- gpg --import arpnetworking.key
- if [ \( -n "${TRAVIS_TAG}" \) -a  "${TRAVIS_PULL_REQUEST}" = "false" ]; then export TARGET="deploy -P release"; fi;
script:
- curl -s ${JDKW} | bash /dev/stdin ./mvnw clean ${TARGET} --settings settings.xml -P rpm -U
